services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/data/postgres
    environment:
      - POSTGRES_USER=boulanger-tracker
      - POSTGRES_PASSWORD=boulanger-tracker
      - POSTGRES_DB=boulanger-tracker

volumes:
  postgresql:
    driver: local
